# Generated by Django 5.2.7 on 2025-12-27 02:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0003_examplesentence_topic_alter_wordtag_options_and_more'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 'Again'), (2, 'Hard'), (3, 'Good'), (4, 'Easy')], verbose_name='Рейтинг FSRS')),
                ('is_correct', models.BooleanField(verbose_name='Правильный ответ')),
                ('response_time', models.FloatField(verbose_name='Время ответа (сек)')),
                ('exercise_type', models.CharField(max_length=50, verbose_name='Тип упражнения')),
                ('review_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата повторения')),
                ('scheduled_days', models.IntegerField(default=0, verbose_name='Запланировано дней')),
            ],
            options={
                'verbose_name': 'Запись повторения',
                'verbose_name_plural': 'Записи повторений',
            },
        ),
        migrations.CreateModel(
            name='UserExerciseHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_type', models.CharField(choices=[('translation', 'Перевод'), ('matching', 'Сопоставление'), ('writing', 'Написание иероглифов'), ('listening', 'Аудирование'), ('multiple_choice', 'Множественный выбор')], max_length=20, verbose_name='Тип задания')),
                ('is_correct', models.BooleanField(verbose_name='Правильный ответ')),
                ('time_spent', models.FloatField(default=0, verbose_name='Время выполнения (секунды)')),
                ('difficulty', models.PositiveSmallIntegerField(default=1, verbose_name='Сложность задания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время выполнения')),
            ],
            options={
                'verbose_name': 'История заданий',
                'verbose_name_plural': 'История заданий',
            },
        ),
        migrations.CreateModel(
            name='UserLearningProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fsrs_weights', models.TextField(default='[]', help_text='Оптимизированные веса для алгоритма FSRS', verbose_name='FSRS веса (JSON)')),
                ('new_cards_per_day', models.IntegerField(default=10, verbose_name='Новых карточек в день')),
                ('max_reviews_per_day', models.IntegerField(default=100, verbose_name='Максимум повторений в день')),
                ('learning_steps', models.JSONField(default=list, verbose_name='Шаги обучения')),
                ('re_learning_steps', models.JSONField(default=list, verbose_name='Шаги переобучения')),
                ('desired_retention', models.FloatField(default=0.9, verbose_name='Желаемое удержание знаний')),
                ('maximum_interval', models.IntegerField(default=36500, verbose_name='Максимальный интервал (дней)')),
            ],
            options={
                'verbose_name': 'Профиль обучения',
                'verbose_name_plural': 'Профили обучения',
            },
        ),
        migrations.CreateModel(
            name='UserLearningStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_lessons_completed', models.IntegerField(default=0, verbose_name='Всего пройдено уроков')),
                ('total_exercises_completed', models.IntegerField(default=0, verbose_name='Всего выполнено заданий')),
                ('total_time_spent', models.IntegerField(default=0, verbose_name='Общее время обучения (секунды)')),
                ('current_streak', models.IntegerField(default=0, verbose_name='Текущая серия дней')),
                ('longest_streak', models.IntegerField(default=0, verbose_name='Самая длинная серия дней')),
                ('last_activity_date', models.DateField(blank=True, null=True, verbose_name='Дата последней активности')),
                ('xp_points', models.IntegerField(default=0, verbose_name='Очки опыта')),
                ('level', models.IntegerField(default=1, verbose_name='Уровень пользователя')),
            ],
            options={
                'verbose_name': 'Статистика обучения',
                'verbose_name_plural': 'Статистика обучения',
            },
        ),
        migrations.CreateModel(
            name='UserTopicProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('words_learned', models.IntegerField(default=0, verbose_name='Слов изучено')),
                ('total_words', models.IntegerField(default=0, verbose_name='Всего слов в теме')),
                ('accuracy', models.FloatField(default=0.0, verbose_name='Точность ответов')),
                ('last_practiced', models.DateTimeField(blank=True, null=True, verbose_name='Последняя практика')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активно изучается')),
                ('mastery_level', models.PositiveSmallIntegerField(default=0, help_text='0-5 (0 - не начато, 5 - освоено)', verbose_name='Уровень освоения')),
            ],
            options={
                'verbose_name': 'Прогресс по теме',
                'verbose_name_plural': 'Прогресс по темам',
            },
        ),
        migrations.RemoveField(
            model_name='userword',
            name='ease_factor',
        ),
        migrations.RemoveField(
            model_name='userword',
            name='is_learned',
        ),
        migrations.RemoveField(
            model_name='userword',
            name='last_reviewed',
        ),
        migrations.RemoveField(
            model_name='userword',
            name='review_count',
        ),
        migrations.AddField(
            model_name='userword',
            name='avg_response_time',
            field=models.FloatField(default=0, verbose_name='Среднее время ответа (сек)'),
        ),
        migrations.AddField(
            model_name='userword',
            name='consecutive_correct',
            field=models.IntegerField(default=0, verbose_name='Подряд правильных ответов'),
        ),
        migrations.AddField(
            model_name='userword',
            name='correct_attempts',
            field=models.IntegerField(default=0, verbose_name='Правильных попыток'),
        ),
        migrations.AddField(
            model_name='userword',
            name='difficulty',
            field=models.FloatField(default=8.0, verbose_name='Сложность слова'),
        ),
        migrations.AddField(
            model_name='userword',
            name='due',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время следующего повторения'),
        ),
        migrations.AddField(
            model_name='userword',
            name='elapsed_days',
            field=models.IntegerField(default=0, verbose_name='Дней с последнего повторения'),
        ),
        migrations.AddField(
            model_name='userword',
            name='lapses',
            field=models.IntegerField(default=0, verbose_name='Количество ошибок'),
        ),
        migrations.AddField(
            model_name='userword',
            name='last_review',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время последнего повторения'),
        ),
        migrations.AddField(
            model_name='userword',
            name='reps',
            field=models.IntegerField(default=0, verbose_name='Количество повторений'),
        ),
        migrations.AddField(
            model_name='userword',
            name='scheduled_days',
            field=models.IntegerField(default=0, verbose_name='Запланировано дней до след. повторения'),
        ),
        migrations.AddField(
            model_name='userword',
            name='stability',
            field=models.FloatField(default=0.0, verbose_name='Стабильность запоминания'),
        ),
        migrations.AddField(
            model_name='userword',
            name='state',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Состояние (0=new, 1=learning, 2=review, 3=relearning)'),
        ),
        migrations.AddField(
            model_name='userword',
            name='total_attempts',
            field=models.IntegerField(default=0, verbose_name='Всего попыток'),
        ),
        migrations.AddIndex(
            model_name='userword',
            index=models.Index(fields=['user', 'due'], name='idx_user_due'),
        ),
        migrations.AddIndex(
            model_name='userword',
            index=models.Index(fields=['due'], name='idx_due'),
        ),
        migrations.AddIndex(
            model_name='userword',
            index=models.Index(fields=['state'], name='idx_state'),
        ),
        migrations.AddField(
            model_name='reviewlog',
            name='user_word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_logs', to='users.userword'),
        ),
        migrations.AddField(
            model_name='userexercisehistory',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dictionary.topic', verbose_name='Тема'),
        ),
        migrations.AddField(
            model_name='userexercisehistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userexercisehistory',
            name='word',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dictionary.word', verbose_name='Слово'),
        ),
        migrations.AddField(
            model_name='userlearningprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='learning_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userlearningstats',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='learning_stats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usertopicprogress',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='dictionary.topic'),
        ),
        migrations.AddField(
            model_name='usertopicprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_progress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='reviewlog',
            index=models.Index(fields=['user_word', 'review_date'], name='idx_review_log_date'),
        ),
        migrations.AddIndex(
            model_name='userexercisehistory',
            index=models.Index(fields=['user', 'created_at'], name='idx_user_exercise_time'),
        ),
        migrations.AddIndex(
            model_name='userexercisehistory',
            index=models.Index(fields=['user', 'exercise_type'], name='idx_user_exercise_type'),
        ),
        migrations.AddIndex(
            model_name='userexercisehistory',
            index=models.Index(fields=['user', 'is_correct'], name='idx_user_correctness'),
        ),
        migrations.AddIndex(
            model_name='usertopicprogress',
            index=models.Index(fields=['user', 'mastery_level'], name='idx_user_mastery'),
        ),
        migrations.AddConstraint(
            model_name='usertopicprogress',
            constraint=models.UniqueConstraint(fields=('user', 'topic'), name='unique_user_topic'),
        ),
    ]
