# Generated by Django 5.2.7 on 2025-12-25 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PartOfSpeech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='Название части слова')),
            ],
            options={
                'verbose_name': 'Часть речи',
                'verbose_name_plural': 'Части речи',
                'indexes': [models.Index(fields=['name'], name='idx_part_of_speech_name')],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='Название тэга')),
            ],
            options={
                'verbose_name': 'Тэг',
                'verbose_name_plural': 'Тэги',
                'indexes': [models.Index(fields=['name'], name='idx_tag_name')],
            },
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hanzi', models.CharField(default='', max_length=32, verbose_name='Иероглифы')),
                ('pinyin_numeric', models.CharField(default='', max_length=255, verbose_name='Пиньинь с цифровым представлением тонов')),
                ('pinyin_graphic', models.CharField(default='', max_length=255, verbose_name='Пиньинь с тональными символами')),
                ('translation', models.TextField(default='', verbose_name='Перевод')),
                ('difficulty', models.PositiveSmallIntegerField(default=0, verbose_name='Сложность слова по стандарту HSK (от 2021 года)')),
            ],
            options={
                'verbose_name': 'Слово',
                'verbose_name_plural': 'Слова',
                'indexes': [models.Index(fields=['hanzi'], name='idx_word_hanzi'), models.Index(fields=['pinyin_numeric'], name='idx_word_pinyin_numeric'), models.Index(fields=['difficulty'], name='idx_word_difficulty')],
            },
        ),
        migrations.CreateModel(
            name='WordComposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(default=1, help_text='Позиция parent_word в child_word')),
                ('child_word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_child', to='dictionary.word')),
                ('parent_word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_words', to='dictionary.word')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('child_word', 'position'), name='unique_position_in_word')],
            },
        ),
        migrations.CreateModel(
            name='WordPartOfSpeech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_of_speech', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_words', to='dictionary.partofspeech')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts_of_speech', to='dictionary.word')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('word', 'part_of_speech'), name='unique_word_part_of_speech')],
            },
        ),
        migrations.CreateModel(
            name='WordTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_words', to='dictionary.tag')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='dictionary.word')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('word', 'tag'), name='unique_word_tag')],
            },
        ),
    ]
