# Generated by Django 5.2.7 on 2025-10-29 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('dictionary_type', models.CharField(choices=[('global', 'Общий словарь'), ('user', 'Пользовательский словарь')], default='user', max_length=10)),
            ],
            options={
                'verbose_name': 'Словарь',
                'verbose_name_plural': 'Словари',
            },
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('traditional', models.CharField(max_length=10, verbose_name='Традиционный')),
                ('simplified', models.CharField(max_length=10, verbose_name='Упрощенный')),
                ('pinyin', models.CharField(max_length=50, verbose_name='Пиньинь')),
                ('translation', models.TextField(verbose_name='Перевод')),
            ],
            options={
                'verbose_name': 'Слово',
                'verbose_name_plural': 'Слова',
            },
        ),
        migrations.CreateModel(
            name='DictionaryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки пользователя')),
                ('dictionary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='dictionary.dictionary')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dictionary_entries', to='dictionary.word')),
            ],
            options={
                'verbose_name': 'Запись словаря',
                'verbose_name_plural': 'Записи словаря',
                'unique_together': {('dictionary', 'word')},
            },
        ),
    ]
