# Generated by Django 5.2.7 on 2025-11-03 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='dictionary',
            constraint=models.UniqueConstraint(condition=models.Q(('dictionary_type', 'global')), fields=('dictionary_type',), name='unique_global_dictionary'),
        ),
    ]
