# Generated by Django 5.2.7 on 2025-12-26 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordcomposition',
            name='child_word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='dictionary.word'),
        ),
        migrations.AlterField(
            model_name='wordcomposition',
            name='parent_word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_in_words', to='dictionary.word'),
        ),
    ]
