# Generated by Django 5.2.7 on 2025-11-03 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0002_dictionary_unique_global_dictionary'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='dictionary',
            name='unique_global_dictionary',
        ),
    ]
