# Generated by Django 5.2.7 on 2025-12-27 02:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0002_alter_wordcomposition_child_word_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExampleSentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chinese_sentence', models.TextField(verbose_name='Предложение на китайском')),
                ('pinyin_sentence', models.TextField(verbose_name='Пиньинь')),
                ('translation', models.TextField(verbose_name='Перевод')),
                ('difficulty', models.PositiveSmallIntegerField(default=1, verbose_name='Сложность предложения')),
            ],
            options={
                'verbose_name': 'Пример предложения',
                'verbose_name_plural': 'Примеры предложений',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Название темы')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('weight', models.FloatField(default=1.0, help_text='Используется для приоритизации в обучении', verbose_name='Вес темы')),
                ('icon', models.CharField(blank=True, max_length=32, verbose_name='Иконка темы')),
                ('difficulty_level', models.PositiveSmallIntegerField(default=1, help_text='1-6 (по аналогии с HSK)', verbose_name='Уровень сложности темы')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок отображения')),
            ],
            options={
                'verbose_name': 'Тема',
                'verbose_name_plural': 'Темы',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='wordtag',
            options={'verbose_name': 'Связь слова с тегом', 'verbose_name_plural': 'Связи слов с тегами'},
        ),
        migrations.AddField(
            model_name='tag',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='tag',
            name='frequency_rank',
            field=models.IntegerField(default=0, help_text='Чем меньше, тем чаще встречается', verbose_name='Ранг частотности'),
        ),
        migrations.AddField(
            model_name='tag',
            name='weight',
            field=models.FloatField(default=1.0, help_text='Используется для приоритизации в обучении', verbose_name='Вес тэга'),
        ),
        migrations.AddField(
            model_name='wordtag',
            name='added_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата добавления'),
        ),
        migrations.AddField(
            model_name='wordtag',
            name='relevance_score',
            field=models.FloatField(default=1.0, help_text='Насколько хорошо слово соответствует тегу (0-1)', verbose_name='Релевантность слова для тега'),
        ),
        migrations.AlterField(
            model_name='wordtag',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_tags', to='dictionary.word'),
        ),
        migrations.AddIndex(
            model_name='wordtag',
            index=models.Index(fields=['word', 'tag'], name='idx_word_tag'),
        ),
        migrations.AddField(
            model_name='examplesentence',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examples', to='dictionary.word', verbose_name='Слово'),
        ),
        migrations.AddField(
            model_name='topic',
            name='parent_topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subtopics', to='dictionary.topic', verbose_name='Родительская тема'),
        ),
        migrations.AddField(
            model_name='tag',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tags', to='dictionary.topic', verbose_name='Тема'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['weight'], name='idx_tag_weight'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['frequency_rank'], name='idx_tag_frequency'),
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['name'], name='idx_topic_name'),
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['difficulty_level'], name='idx_topic_difficulty'),
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['is_active'], name='idx_topic_active'),
        ),
    ]
