# Generated by Django 5.2.7 on 2025-11-03 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0003_remove_dictionary_unique_global_dictionary'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='word',
            index=models.Index(fields=['simplified'], name='dictionary__simplif_8bced2_idx'),
        ),
        migrations.AddIndex(
            model_name='word',
            index=models.Index(fields=['traditional'], name='dictionary__traditi_815375_idx'),
        ),
        migrations.AddIndex(
            model_name='word',
            index=models.Index(fields=['pinyin'], name='dictionary__pinyin_5b39f6_idx'),
        ),
    ]
