# Generated by Django 5.2.7 on 2026-08-02 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0003_examplesentence_topic_alter_wordtag_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(default='en', max_length=8)),
                ('text', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='WordStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='WordStructureType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='WordTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_primary', models.BooleanField(default=False)),
                ('source', models.CharField(blank=True, default='', max_length=64)),
            ],
            options={
                'ordering': ['word', 'order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=models.SlugField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='slug',
            field=models.SlugField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='word',
            name='frequency_rank',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='word',
            name='radical',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='word',
            name='traditional',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddIndex(
            model_name='word',
            index=models.Index(fields=['frequency_rank'], name='idx_word_frequency'),
        ),
        migrations.AddIndex(
            model_name='translation',
            index=models.Index(fields=['language', 'text'], name='idx_translation_lang_text'),
        ),
        migrations.AddConstraint(
            model_name='translation',
            constraint=models.UniqueConstraint(fields=('language', 'text'), name='unique_translation_language_text'),
        ),
        migrations.AddField(
            model_name='wordstructure',
            name='word',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='structure', to='dictionary.word'),
        ),
        migrations.AddIndex(
            model_name='wordstructuretype',
            index=models.Index(fields=['slug'], name='idx_word_structure_slug'),
        ),
        migrations.AddField(
            model_name='wordstructure',
            name='structure_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='word_structures', to='dictionary.wordstructuretype'),
        ),
        migrations.AddField(
            model_name='wordtranslation',
            name='translation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_links', to='dictionary.translation'),
        ),
        migrations.AddField(
            model_name='wordtranslation',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_translations', to='dictionary.word'),
        ),
        migrations.AddIndex(
            model_name='wordtranslation',
            index=models.Index(fields=['word', 'order'], name='idx_word_translation_order'),
        ),
        migrations.AddIndex(
            model_name='wordtranslation',
            index=models.Index(fields=['translation'], name='idx_word_translation_value'),
        ),
        migrations.AddConstraint(
            model_name='wordtranslation',
            constraint=models.UniqueConstraint(fields=('word', 'translation'), name='unique_word_translation'),
        ),
    ]
