# Generated by Django 5.2.7 on 2025-11-03 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0004_word_dictionary__simplif_8bced2_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='pinyin',
            field=models.CharField(max_length=255, verbose_name='Пиньинь'),
        ),
        migrations.AlterField(
            model_name='word',
            name='simplified',
            field=models.CharField(max_length=20, verbose_name='Упрощенный'),
        ),
        migrations.AlterField(
            model_name='word',
            name='traditional',
            field=models.CharField(max_length=20, verbose_name='Традиционный'),
        ),
    ]
