# Generated by Django 5.2.7 on 2025-12-27 02:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dictionary', '0003_examplesentence_topic_alter_wordtag_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_xp', models.IntegerField(default=100, verbose_name='Цель по XP')),
                ('target_words', models.IntegerField(default=10, verbose_name='Цель по словам')),
                ('target_time', models.IntegerField(default=30, verbose_name='Цель по времени (минуты)')),
                ('current_xp', models.IntegerField(default=0, verbose_name='Текущий XP')),
                ('current_words', models.IntegerField(default=0, verbose_name='Текущие слова')),
                ('current_time', models.IntegerField(default=0, verbose_name='Текущее время (минуты)')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('completed', models.BooleanField(default=False, verbose_name='Выполнено')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='daily_goal', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Дневная цель',
                'verbose_name_plural': 'Дневные цели',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Название урока')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('difficulty', models.PositiveSmallIntegerField(default=1, help_text='1-легкий, 2-средний, 3-сложный', verbose_name='Сложность урока')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок в теме')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('estimated_time', models.IntegerField(default=10, verbose_name='Примерное время выполнения (минуты)')),
                ('xp_reward', models.IntegerField(default=100, verbose_name='Награда за прохождение (XP)')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='dictionary.topic', verbose_name='Тема')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
                'ordering': ['topic', 'order', 'difficulty'],
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_type', models.CharField(choices=[('translation_ru', 'Перевод на русский'), ('translation_cn', 'Перевод на китайский'), ('matching', 'Сопоставление'), ('writing', 'Написание иероглифов'), ('listening', 'Аудирование'), ('multiple_choice', 'Множественный выбор'), ('fill_gap', 'Заполнение пропусков')], max_length=20, verbose_name='Тип задания')),
                ('question', models.TextField(verbose_name='Вопрос/задание')),
                ('correct_answer', models.TextField(verbose_name='Правильный ответ')),
                ('options', models.JSONField(blank=True, default=list, help_text='Для заданий с выбором', verbose_name='Варианты ответов (JSON)')),
                ('difficulty', models.PositiveSmallIntegerField(default=1, verbose_name='Сложность')),
                ('explanation', models.TextField(blank=True, verbose_name='Объяснение')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок в уроке')),
                ('additional_words', models.ManyToManyField(blank=True, related_name='exercise_additional', to='dictionary.word', verbose_name='Дополнительные слова')),
                ('word', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='dictionary.word', verbose_name='Основное слово')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='learning.lesson', verbose_name='Урок')),
            ],
            options={
                'verbose_name': 'Упражнение',
                'verbose_name_plural': 'Упражнения',
                'ordering': ['lesson', 'order'],
            },
        ),
        migrations.CreateModel(
            name='UserLessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False, verbose_name='Завершен')),
                ('score', models.FloatField(default=0.0, verbose_name='Оценка за урок')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Начало')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершение')),
                ('attempts', models.IntegerField(default=0, verbose_name='Попытки')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='learning.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Прогресс урока',
                'verbose_name_plural': 'Прогресс уроков',
                'constraints': [models.UniqueConstraint(fields=('user', 'lesson'), name='unique_user_lesson')],
            },
        ),
    ]
