# Generated by Django 5.2.7 on 2026-08-02 02:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0003_examplesentence_topic_alter_wordtag_options_and_more'),
        ('learning', '0005_practice_session_planning_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciseattempt',
            name='fsrs_rating',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='MemoryCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(max_length=32)),
                ('fsrs_state', models.JSONField(blank=True, default=dict)),
                ('due_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('last_review_at', models.DateTimeField(blank=True, null=True)),
                ('scheduler_version', models.CharField(default='fsrs-py', max_length=32)),
                ('parameter_set_version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('learning_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memory_cards', to='dictionary.word')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memory_cards', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AttemptMemoryCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('score', models.DecimalField(decimal_places=4, default=0, max_digits=6)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('fsrs_rating', models.PositiveIntegerField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, default='', max_length=64)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memory_card_links', to='learning.exerciseattempt')),
                ('memory_card', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempt_links', to='learning.memorycard')),
            ],
        ),
        migrations.CreateModel(
            name='MemoryReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField()),
                ('reviewed_at', models.DateTimeField()),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('previous_state', models.JSONField(blank=True, default=dict)),
                ('resulting_state', models.JSONField(blank=True, default=dict)),
                ('fsrs_log', models.JSONField(blank=True, default=dict)),
                ('scheduler_version', models.CharField(max_length=32)),
                ('parameter_set_version', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exercise_attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memory_reviews', to='learning.exerciseattempt')),
                ('memory_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='learning.memorycard')),
            ],
        ),
        migrations.CreateModel(
            name='FSRSSchedulerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameters', models.JSONField(blank=True, default=list)),
                ('desired_retention', models.DecimalField(decimal_places=3, default=0.9, max_digits=4)),
                ('learning_steps', models.JSONField(blank=True, default=list)),
                ('relearning_steps', models.JSONField(blank=True, default=list)),
                ('maximum_interval_days', models.PositiveIntegerField(default=36500)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fsrs_scheduler_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'is_active'], name='idx_fsrs_profile_user_active')],
                'constraints': [models.UniqueConstraint(fields=('user', 'version'), name='unique_fsrs_profile_user_version')],
            },
        ),
        migrations.AddIndex(
            model_name='memorycard',
            index=models.Index(fields=['user', 'due_at'], name='idx_memory_card_user_due'),
        ),
        migrations.AddIndex(
            model_name='memorycard',
            index=models.Index(fields=['user', 'direction'], name='idx_memory_card_user_direction'),
        ),
        migrations.AddConstraint(
            model_name='memorycard',
            constraint=models.UniqueConstraint(fields=('user', 'learning_item', 'direction'), name='unique_memory_card_direction'),
        ),
        migrations.AddIndex(
            model_name='attemptmemorycard',
            index=models.Index(fields=['memory_card'], name='idx_attempt_memory_card'),
        ),
        migrations.AddIndex(
            model_name='attemptmemorycard',
            index=models.Index(fields=['attempt', 'position'], name='idx_attempt_memory_position'),
        ),
        migrations.AddConstraint(
            model_name='attemptmemorycard',
            constraint=models.UniqueConstraint(fields=('attempt', 'memory_card'), name='unique_attempt_memory_card'),
        ),
        migrations.AddConstraint(
            model_name='attemptmemorycard',
            constraint=models.UniqueConstraint(fields=('attempt', 'position'), name='unique_attempt_memory_card_position'),
        ),
        migrations.AddIndex(
            model_name='memoryreview',
            index=models.Index(fields=['memory_card', 'reviewed_at'], name='idx_memory_review_card_time'),
        ),
        migrations.AddIndex(
            model_name='memoryreview',
            index=models.Index(fields=['exercise_attempt'], name='idx_memory_review_attempt'),
        ),
    ]
