# Generated by Django 5.2.7 on 2026-08-02 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0006_exerciseattempt_fsrs_rating_memorycard_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseEventConsumerReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumer_name', models.CharField(max_length=128)),
                ('event_id', models.UUIDField()),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='memoryreview',
            constraint=models.UniqueConstraint(fields=('memory_card', 'exercise_attempt'), name='unique_memory_review_card_attempt'),
        ),
        migrations.AddIndex(
            model_name='exerciseeventconsumerreceipt',
            index=models.Index(fields=['consumer_name', 'processed_at'], name='idx_evt_receipt_cons_time'),
        ),
        migrations.AddConstraint(
            model_name='exerciseeventconsumerreceipt',
            constraint=models.UniqueConstraint(fields=('consumer_name', 'event_id'), name='unique_exercise_event_consumer_receipt'),
        ),
    ]
