# Generated by Django 5.2.7 on 2026-08-02 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0008_backfill_legacy_exercise_attempt_snapshots'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='slug',
            field=models.SlugField(blank=True, max_length=96, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='PracticeConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=96, unique=True)),
                ('value', models.JSONField(blank=True, default=dict)),
                ('description', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['key'],
                'indexes': [models.Index(fields=['key'], name='idx_practice_config_key')],
            },
        ),
    ]
